### ISSUE TITLE
Onvif Device Manager can't 'discover' this device?

### ISSUE THREAD

**Issue by mxyIteris** [KoynovStas/onvif_srvd#12]
GREAT template! I just have a simple question.
I have the sample server (onvif_srvd) running on my linux device address 192.168.200.2 by running the provided script 'S90onvif_srvd start'

I can talk to the onvif_srvd using the other linux client sample by running the command ./ipconvif 192.168.200.2:1000

But when I run the suggested Onvif Device Manager on windows, I cannot 'discover' the device that's running onvif_srvd. What should I do to make the device discoverable?

**Comment by KoynovStas** [comment]
This template does not include ONVIF WS-Discovery service. I extracted it to a separate daemon (see [wsdd](https://github.com/KoynovStas/wsdd)). You can bind one ONVIF server to several Ethernet ports !. To do this, run  [wsdd](https://github.com/KoynovStas/wsdd) with different ports eth0, eth1 etc. Or use my  [wsdd](https://github.com/KoynovStas/wsdd) daemon with different ONVIF daemons.
