### ISSUE TITLE
Media2  Service support

### ISSUE THREAD

**Issue by parinpatel** [KoynovStas/onvif_srvd#14]
@KoynovStas 
When will you provide the support of Media2(ver20)  Service in your repository and Is there any other repository which will provide the support of it?

**Comment by KoynovStas** [comment]
Hey. To be honest, I don’t know. Today I came from a business trip. I have not been home for 2 weeks. The only thing I want is to sleep. I can’t accept the PR half a year (dude added support for PTZ). I just don’t have time, just the employer has arrogant! Therefore, I just can’t promise anything.

**Comment by parinpatel** [comment]
ok, Got it.
