### ISSUE TITLE
Build failure due to missing fcntl.h include

### ISSUE THREAD

**Issue by ashway83** [KoynovStas/onvif_srvd#16]
On Apline Linux build fails due to missing fcntl.h include. After adding missing include into daemon.c build succeeds:
``` 
#include <fcntl.h>

```
g++ -c src/daemon.c -o src/daemon_debug.o  -DDEBUG  -g  -DDAEMON_NAME='"onvif_srvd"' -DDAEMON_MAJOR_VERSION=1 -DDAEMON_MINOR_VERSION=1 -DDAEMON_PATCH_VERSION=0 -DDAEMON_PID_FILE_NAME='"onvif_srvd.pid"' -DDAEMON_LOG_FILE_NAME='"onvif_srvd.log"' -DDAEMON_NO_CHDIR=1 -DDAEMON_NO_CLOSE_STDIO=1 -I./src -I./generated -I./gsoap-2.8/gsoap -I./gsoap-2.8/gsoap/custom -I./gsoap-2.8/gsoap/plugin -I./gsoap-2.8/gsoap/import -std=c++11 -O2  -Wall  -pipe
src/daemon.c: In function 'int redirect_stdio_to_devnull()':
src/daemon.c:170:28: error: 'O_RDWR' was not declared in this scope
  170 |     fd = open("/dev/null", O_RDWR);
      |                            ^~~~~~
src/daemon.c:170:10: error: 'open' was not declared in this scope; did you mean 'popen'?
  170 |     fd = open("/dev/null", O_RDWR);
      |          ^~~~
      |          popen
src/daemon.c: In function 'int create_pid_file(const char*)':
src/daemon.c:204:30: error: 'O_RDWR' was not declared in this scope
  204 |     fd = open(pid_file_name, O_RDWR | O_CREAT, 0644);
      |                              ^~~~~~
src/daemon.c:204:39: error: 'O_CREAT' was not declared in this scope
  204 |     fd = open(pid_file_name, O_RDWR | O_CREAT, 0644);
      |                                       ^~~~~~~
src/daemon.c:204:10: error: 'open' was not declared in this scope; did you mean 'popen'?
  204 |     fd = open(pid_file_name, O_RDWR | O_CREAT, 0644);
      |          ^~~~
      |          popen
make: *** [Makefile:162: src/daemon_debug.o] Error 1

**Comment by KoynovStas** [comment]
Fixed in commit: 39b2da4d9e40141 from PR #13
