### ISSUE TITLE
WS-Security Isn't working [I did compiled with WSSE_ON=1]

### ISSUE THREAD

**Issue by thewh1teagle** [KoynovStas/onvif_srvd#28]
Hi! 
I compiled this program with the flag ```make WSSE_ON=1``` for ```WS-Security```

```onvid_srvd``` is started with user and password options :

```
1466 root ./onvif_srvd --pid_file /var/run/onvif_srvd.pid --model
MJSXJ02CM --manufacturer Xiaomi --firmware_ver 3.4.2_0062 --ifs wlan0
--port 5000 --scope onvif://www.onvif.org/Profile/S --name HD --width 
1920 --height 1080 --url rtsp://192.168.1.47:8554/mainstream --type H264
--user XXXXX --password YYYYYY --ptz --move_left eval echo pan forward 5 
 /mnt/sdcard/hacks/motor_control/event --move_right eval echo pan reverse 5 > /mnt/sdcard/hacks/motor_control/event --move_up eval echo tilt forward 5 > /mnt/sdcard/hacks/motor_control/event --move_down eval echo tilt reverse 5 > /mnt/sdcard/hacks/motor_control/event
```
But still, If I use ```onvifer``` on my phone, I did not configure any account
and password and I'm still able to access the webcam.

Here is my ```fork``` of this repo
https://github.com/thewh1teagle/onvif_srvd

Thanks!

**Comment by KoynovStas** [comment]
This is a duplicate question!. See issue #1.
The server has only the minimum implementation and validation there is no password!

You must implement the login-password check yourself!
`make WSSE_ON=1` is needed for correct linking of libraries and parameters for gsoap.

**Comment by thewh1teagle** [comment]
Thank you very much!
