### ISSUE TITLE
compile on windows

### ISSUE THREAD

**Issue by p3im4n** [KoynovStas/onvif_srvd#29]
hi
thanks for  your good project
how can i compile it on windows?
and after that how can I feed a video stream to it?
for example I feed it a movie ,and nvr device(client) play move as onvif camera main stream!

best regards

**Comment by KoynovStas** [comment]
The app is a Linux daemon. It use the Linux API. I don't know how it can be run on Windows.

**Comment by p3im4n** [comment]
id it tested by hardware nvr too?

**Comment by KoynovStas** [comment]
I don't have a DVR. I was writing an app for our flame detector. there is a video recorder on the object, but I do not know whether it is hardware or software. He understands our camera.

**Comment by p3im4n** [comment]
thx for your fast response Mr KoynovStas :1st_place_medal:
