### ISSUE TITLE
support for h265

### ISSUE THREAD

**Issue by belkone** [KoynovStas/onvif_srvd#38]
hi, I use your server for several cameras and it works great, but some of them only support h265 and I can’t use there onvif_srvd.
Are you planning to add support for h265? :)

**Comment by KoynovStas** [comment]
I have implemented the minimal version of the S-profile. It does not support H.265. There is a certain profile of Media2 there is support. but I don’t have time to do this, in my free time I’ll better take care of my template for calculating CRC, and the transition to C++11.
more information about the H.265 can be found here: https://ipvm.com/reports/onvif-h265

**Comment by belkone** [comment]
ok, thanks for reply.
