### ISSUE TITLE
PTZ is not showing up in ODM

### ISSUE THREAD

**Issue by NolanMaverick** [KoynovStas/onvif_srvd#46]
Hello,
           I'm working on RPI 4 Model B, I'm able to stream USB camera connected to RPI, in ONVIF Device Manager, but I can't able to see settings to control PTZ.
           
           
  This is what I'm getting now
  

![SRVD](https://github.com/KoynovStas/onvif_srvd/assets/140538620/43fd0bef-ebfe-437e-b2f1-845171f784ed)

But this is what I'm expecting

![PTZ](https://github.com/KoynovStas/onvif_srvd/assets/140538620/5d51b9cd-61d0-4728-b5c4-762cd5844b91)

So how to configure to enable PTZ control.

Regards,
Nolan

**Comment by KoynovStas** [comment]
This problem can be solved very simply. You should have read the output of the `--help` command. The `--ptz` parameter will be specified there, which will enable PTZ support. I foresee the next question, why there is no reaction to PTZ commands. Answer: You must add commands as command line options or directly in the code. How to do it? Well, just studying the code.
