### ISSUE TITLE
How to create users through Onvif in RPI

### ISSUE THREAD

**Issue by NolanMaverick** [KoynovStas/onvif_srvd#47]
Hello,
I'm trying to Implement **CreateUsers**, still did not get how to create users using **CreateUsers in ServiceDevice.cpp** and soap_new_set_tt__User.
Can anyone help one how to create users?

Regards,
Nolan

**Comment by KoynovStas** [comment]
Do I understand correctly that you have resolved the issue with the PTZ?

**Comment by KoynovStas** [comment]
onvif_srvd - This is a minimal working template for the server. Its implementation supports sending a link to an RTSP stream. You must implement all other functionality yourself. You must implement adding users, etc. yourself.
