### ISSUE TITLE
Have you got any ideas about on which functions should check the wsse?

### ISSUE THREAD

**Issue by jemyzhang** [KoynovStas/onvif_srvd#7]
For example GetCapabilities can be retrieved without credentials supplied,  but I can't found the detail information about this on onvif specifications.

**Comment by KoynovStas** [comment]
I think you should see the documents from ONVIF: [Device Test Specifications](https://www.onvif.org/profiles/conformance/device-test/)

**Comment by jemyzhang** [comment]
Thanks, I've found the spec from each core spec.
