### ISSUE TITLE
memory peak

### ISSUE THREAD

**Issue by Micah2015** [KoynovStas/onvif_srvd#8]
Help! I find when the program run for a long time, memory increase infinitely. Is anybody have this situation? Thanks!

**Comment by Micah2015** [comment]
I add `soap_destroy(soap); soap_end(soap);` in the main while loop end, build release mode, seems solved this problem

**Comment by KoynovStas** [comment]
Thanks for the message. But why did you need to do this in the main loop?
You should have completed the daemon via the **SIGTERM** signal, which will call the `daemon_exit_handler` handler. Use [start_scripts](https://github.com/KoynovStas/onvif_srvd/tree/master/start_scripts)
